import { ReactComponent as BookIcon } from '../assets/categories/book.svg';
import { ReactComponent as SportsIcon } from '../assets/categories/sports.svg';
import { ReactComponent as MediaIcon } from '../assets/categories/media.svg';
import { ReactComponent as ReligionIcon } from '../assets/categories/religion.svg';
import { ReactComponent as TechnologyIcon } from '../assets/categories/technology.svg';
import { ReactComponent as CuisineIcon } from '../assets/categories/cuisine.svg';
import { ReactComponent as AgricultureIcon } from '../assets/categories/agriculture.svg';
import { ReactComponent as GeographyIcon } from '../assets/categories/geography.svg';
import { ReactComponent as HistoryIcon } from '../assets/categories/history.svg';
import { ReactComponent as AutoIcon } from '../assets/categories/cars.svg';
import { ReactComponent as CurrentIcon } from '../assets/categories/current-affairs.svg';
import { ReactComponent as PoliticsIcon } from '../assets/categories/politics.svg';
import { ReactComponent as AnimalsIcon } from '../assets/categories/animals.svg';
import { ReactComponent as ProgrammingIcon } from '../assets/categories/programming.svg';
import { ReactComponent as MathsIcon } from '../assets/categories/mathematics.svg';
import { ReactComponent as ScienceIcon } from '../assets/categories/science.svg';
import { ReactComponent as ArtsIcon } from '../assets/categories/art.svg';
import { ReactComponent as LawIcon } from '../assets/categories/law.svg';
import { ReactComponent as NatureIcon } from '../assets/categories/nature.svg';
import { ReactComponent as BusinessIcon } from '../assets/categories/business.svg';
import { ReactComponent as PopIcon } from '../assets/categories/pop.svg';
import { ReactComponent as LanguagesIcon } from '../assets/categories/languages.svg';
import { ReactComponent as HobbiesIcon } from '../assets/categories/hobbies.svg';
import { ReactComponent as SpaceIcon } from '../assets/categories/space.svg';
import { ReactComponent as ArchitectureIcon } from '../assets/categories/architecture.svg';
import { ReactComponent as HealthIcon } from '../assets/categories/health.svg';
import { ReactComponent as TravelIcon } from '../assets/categories/travel.svg';
import { ReactComponent as PsychologyIcon } from '../assets/categories/psychology.svg';
import { ReactComponent as PhilosophyIcon } from '../assets/categories/philosophy.svg';
import { ReactComponent as LiteratureIcon } from '../assets/categories/literature.svg';
import { ReactComponent as MusicIcon } from '../assets/categories/music.svg';
import { ReactComponent as MovieIcon } from '../assets/categories/movies.svg';
import { ReactComponent as GameIcon } from '../assets/categories/games.svg';
import { ReactComponent as GeneralIcon } from '../assets/categories/general.svg';
import { ReactComponent as AviationIcon } from '../assets/categories/aviation.svg';
import { ReactComponent as CountriesIcon } from '../assets/categories/countries.svg';
import { ReactComponent as CelebritiesIcon } from '../assets/categories/celebrities.svg';

const categoryGroups = {
  Education: {
    Icon: BookIcon,
    keywords: [
      'education',
      'books',
      'learning',
      'agriculture',
      'biology',
      'abbreviations',
      'acronyms',
      'arithmetic',
      'college',
      'colleges',
      'mathematics',
      'numbers',
      'nursery_rhymes',
      'pseudonyms',
      'shapes',
      'symbols',
      'zoology',
    ],
  },
  Sports: {
    Icon: SportsIcon,
    keywords: [
      'sports',
      'football',
      'basketball',
      'cricket',
      'tennis',
      'american_football',
      'athletes',
      'athletics',
      'baseball',
      'boxing',
      'climbing',
      'cycling',
      'darts',
      'exercise',
      'fishing',
      'formula_1',
      'games',
      'golf',
      'gymnastics',
      'horse_racing',
      'champions',
      'hockey',
      'nba',
      'olympics',
      'rugby',
      'sailing',
      'soccer',
      'sport',
      'sport_and_leisure',
      'swimming',
      'tennis',
      'track_and_field',
      'winter_sports',
      'world_cup',
      'world_leaders',
    ],
  },
  Entertainment: {
    Icon: MediaIcon,
    keywords: [
      'entertainment',
      'movies',
      'music',
      'theater',
      'films',
      'comedy',
      'acting',
      'actors',
      'advertising',
      'albums',
      'album_artwork',
      'academy_awards',
      '\nrock',
      'amusement_parks',
      'cartoons',
      'childrens_tv',
      'abba',
      'ballet',
      'bands',
      'batman',
      'brands',
      'comedy',
      'comics',
      'awards',
      'dance',
      'directors',
      'disney',
      'duels',
      'fairy_tales',
      'fantasy',
      'fiction',
      'fictitious_characters',
      'folklore',
      'media',
      'marvel',
      'opera',
    ],
  },
  Religion: {
    Icon: ReligionIcon,
    keywords: [
      'religion',
      'christianity',
      'islam',
      'hinduism',
      'buddhism',
      'bible',
      'demonyms',
      'holy_roman_empire',
      'judaism',
      'sikhism',
      'spirits',
      'spirituality',
      'supernatural',
      'superstitions',
      'tarot',
      'witchcraft',
      'witches',
      'zodiac',
    ],
  },
  Technology: {
    Icon: TechnologyIcon,
    keywords: [
      'technology',
      'computing',
      'ai',
      'programming',
      'agile_methodologies',
      '\ttelecommunications',
      'computing',
      'cryptography',
      'electronics',
      'manufacturing',
      'mechanics',
      'radio',
      'the_internet',
      'tools',
      'toys',
      'tv',
    ],
  },
  Cuisine: {
    Icon: CuisineIcon,
    keywords: [
      'cuisine',
      'food',
      'cooking',
      'baking',
      'alcohol',
      'barbeque',
      'beer',
      'bread',
      'breakfast',
      'cakes',
      'candy',
      'cheese',
      'cocktails',
      'coffee',
      'dairy',
      'desserts',
      'drink',
      'drinking',
      'drinks',
      'fast_food',
      'food',
      'food_and_drink',
      'fruit',
      'italian_cuisine',
      'ingredients',
      'liquor',
      'meat',
      'mexican_cuisine',
      'nutrition',
      'nuts',
      'pastry',
      'pork',
      'recipes',
      'restaurants',
      'salad',
      'sandwiches',
      'sauces',
      'seafood',
      'soups',
      'spices',
      'sushi',
      'vegetables',
      'wine',
    ],
  },
  Agriculture: {
    Icon: AgricultureIcon,
    keywords: [
      'agriculture',
      'farms',
      'crops',
      'fish',
      'flowers',
      'fruit',
      'gardening',
      'grains',
      'herbs',
      'nuts',
      'plants',
    ],
  },
  Geography: {
    Icon: GeographyIcon,
    keywords: [
      'geography',
      'geography ',
      'bodies_of_water',
      'canals',
      'bridges',
      'bays',
      'continents',
      'borders',
      'countries',
      'capital_cities',
      'state_capitals',
      'cities',
      'maps',
      'africa',
      'asia',
      'antarctica',
      'caribbean',
      'culture',
      'deserts',
      'earthquakes',
      'europe',
      'events',
      'islands',
      'mediterranean',
      'lakes',
      'landmarks',
      'maps',
      'mountains',
      'pacific_ocean',
      'peninsulas',
      'places',
      'planets',
      'ports',
      'rainforests',
      'rivers',
      'roads',
      'seas',
      'towns',
      'traditions',
      'universities',
      'volcanoes',
      'weather',
    ],
  },
  History: {
    Icon: HistoryIcon,
    keywords: [
      'history',
      'wars',
      'ancient',
      'medieval',
      'ancient_egypt',
      'ancient_greece',
      'american_civil_war',
      'american_revolution',
      "00's",
      '1000s',
      '1300s',
      "1400's",
      '1500s',
      "1600's",
      '1600s',
      "1700's",
      "1800's",
      "1900's",
      "1910's",
      "1920's",
      "1930's",
      "1940's",
      "1950's",
      "1960's",
      "1970's",
      "1980's",
      '1980s',
      "1990's",
      "2000's",
      "2010's",
      '2022',
      '90s',
      'assassinations',
      'battles',
      'cold_war',
      'communism',
      'conquest',
      'controversies',
      'dates',
      'decades',
      'dictators',
      'elections',
      'disasters',
      'empires',
      'festivals',
      'kings',
      'legends',
      'middle_ages',
      'mongolian_empire',
      'monarchs',
      'leaders',
      'leadership',
      'medieval',
      'mythological_creatures',
      'mythology',
      'myths',
      'napoleon',
      'napoleonic_wars',
      'native_americans',
      'ottoman_empire',
      'records',
      'renaissance',
      'revolution',
      'revolutions',
      'romans',
      'reform',
      'saxons',
      'the_ancient_world',
      'the_crusades',
      'vietnam_war',
      'world_war_1',
      'world_war_2',
      'world_war_II',
      'the_romans',
      'treaties',
      'vikings',
      'war',
      'war_of_the_roses',
      'wars',
    ],
  },
  Automotive: {
    Icon: AutoIcon,
    keywords: [
      'cars',
      'automotive',
      'vehicles',
      'boats',
      'driving',
      'motoring',
    ],
  },
  CurrentAffairs: {
    Icon: CurrentIcon,
    keywords: [
      'current affairs',
      'news',
      'politics',
      'newspapers',
      'politics',
      'presidents',
      'companies',
      'government',
      'trade',
    ],
  },
  Animals: {
    Icon: AnimalsIcon,
    keywords: [
      'animals',
      'bugs',
      'wildlife',
      'pets',
      'birds',
      'cats',
      'dinosaurs',
      'dogs',
      'horses',
      'insects',
      'primates',
      'reptiles',
      'snakes',
      'spiders',
      'vampires',
      'zombies',
    ],
  },
  Sciences: {
    Icon: ScienceIcon,
    keywords: [
      'sciences',
      'physics',
      'chemistry',
      'biology',
      'anatomy',
      'anthropology',
      'astronomy',
      'astrophysics',
      'atoms',
      'astrology',
      'archaeology',
      'botany',
      'chemical_elements',
      'chemistry',
      'civil_engineering',
      'endocrinology',
      'engineering',
      'epidemiology',
      'etymology',
      'elements',
      'gases',
      'genetics',
      'geology',
      'geometry',
      'paleontology',
      'particle_physics',
      'physics',
      'physiology',
      'radiation',
      'science',
      'science_fiction',
      'scientific_discoveries',
      'seismology',
    ],
  },
  Arts: {
    Icon: ArtsIcon,
    keywords: [
      'arts',
      'painting',
      'sculpture',
      'design',
      'album_artwork',
      'artists',
      'arts_and_literature',
      'designers',
      'gothic',
      'martial_arts',
      'materials',
      'metals',
      'meteorology',
      'minerals',
      'mining',
      'measurements',
      'painting',
      'paintings',
      'photography',
      'performers',
      'sculpture',
      'theater',
      'theatre',
    ],
  },
  Law: {
    Icon: LawIcon,
    keywords: [
      'law',
      'legal',
      'court',
      'justice',
      'censorship',
      'civil_rights',
      'classics',
      'rules',
      'the_constitution',
    ],
  },
  Celebrities: {
    Icon: CelebritiesIcon,
    keywords: [
      'people',
      'british_prime_ministers',
      'charles_dickens',
      'bob_dylan',
      'elvis_presley',
      'james_bond',
      'mardi_gras',
      'marilyn_monroe',
      'nicknames',
      'previous_names',
      'outlaws',
      'pioneers',
      'pirates',
      'queens',
      'royalty',
      'saints',
      'scandals',
      'speeches',
      'weddings',
      'women',
      'woody_allen',
    ],
  },
  Nature: {
    Icon: NatureIcon,
    keywords: [
      'nature',
      'environment',
      'ecology',
      'climate',
      'conservation',
      'exploration',
      'explorers',
      'marine_life',
      'natural_disasters',
      'natural_wonders',
      'oceans',
      'trees',
    ],
  },
  Business: {
    Icon: BusinessIcon,
    keywords: [
      'business',
      'economics',
      'finance',
      'currency',
      'decathlon',
      'economics',
      'economy',
      'marketing',
      'organisations',
      'organizations',
      'project_management',
      'retail',
      'scrum',
    ],
  },
  PopCulture: {
    Icon: PopIcon,
    keywords: [
      'celebrities',
      'tv shows',
      'fashion',
      'feminism',
      'festivals',
      'jewelry',
      'kpop',
      'models',
      'one_hit_wonders',
      'pop',
      'pop_music',
      'shoes',
      'slang',
      'slogans',
    ],
  },
  Languages: {
    Icon: LanguagesIcon,
    keywords: [
      'languages',
      'language',
      'linguistics',
      'translations',
      'collective_nouns',
      'alphabet',
      'french',
      'grammar',
      'hebrew',
      'idioms',
      'latin',
      'vocabulary',
      'spanish',
      'translations',
      'words',
    ],
  },
  Hobbies: {
    Icon: HobbiesIcon,
    keywords: ['hobbies', 'crafts', 'diy', 'hunting'],
  },
  Space: {
    Icon: SpaceIcon,
    keywords: [
      'space',
      'astronomy',
      'astrophysics',
      'earth',
      'space_exploration',
      'stars',
      'the_solar_system',
    ],
  },
  Architecture: {
    Icon: ArchitectureIcon,
    keywords: [
      'architecture',
      'buildings',
      'structures',
      'building',
      'castles',
      'infrastructure',
      'skyscrapers',
      'stadiums',
      'statues',
    ],
  },
  Health: {
    Icon: HealthIcon,
    keywords: [
      'health',
      'medicine',
      'fitness',
      'bones',
      'babies',
      'childbirth',
      'dentistry',
      'disease',
      'diseases',
      'drugs',
      'hair',
      'healthcare',
      'herbs',
      'medicine',
      'muscles',
      'neuroscience',
      'ophthalmology',
      'pharmaceuticals',
      'skincare',
      'the_human_body',
    ],
  },
  Travel: {
    Icon: TravelIcon,
    keywords: [
      'travel',
      'tourism',
      'destinations',
      'museums',
      'lakes',
      'landmarks',
      'maps',
      'mountains',
      'natural_wonders',
      'places',
      'pool',
      'prison',
      'restaurants',
      'rivers',
      'roads',
      'seas',
      'seafaring',
      'statues',
      'theme_parks',
      'tourist_attractions',
      'towns',
      'trains',
      'transportation',
      'waterfalls',
    ],
  },
  Psychology: {
    Icon: PsychologyIcon,
    keywords: ['psychology', 'mental health', 'behavior'],
  },
  Philosophy: {
    Icon: PhilosophyIcon,
    keywords: ['philosophy', 'ethics', 'logic'],
  },
  Literature: {
    Icon: LiteratureIcon,
    keywords: [
      'literature',
      'novels',
      'poetry',
      'arts_and_literature',
      'childrens_literature',
      'classic_novels',
      'authors',
      'books',
      'harry_potter',
      'lord_of_the_rings',
      'novel',
      'novels',
      'opening_lines',
      'phrases',
      'playwrights',
      'poetry',
      'print_media',
      'quotes',
      'romance',
      'romantic_comedies',
      'romeo_and_juliet',
      'sayings',
      'shakespeare',
      'sherlock_holmes',
      'short_stories',
      'writing',
    ],
  },
  General: {
    Icon: GeneralIcon,
    keywords: [
      'ceramics',
      'charities',
      'christmas',
      'celebrations',
      'clothing',
      'colonialism',
      'colours',
      'communication',
      'consumer_products',
      'arthurian',
      'crime',
      'beauty',
      'first_lines',
      'firsts',
      'florence',
      'french_new_wave',
      'furniture',
      'general_knowledge',
      'fabric',
      'jewelry',
      'halloween',
      'hats',
      'hock',
      'holidays',
      'hollywood',
      'initials',
      'intelligence',
      'inventions',
      'inventors',
      'leaders',
      'leadership',
      'lgbtq',
      'logos',
      'love',
      'marriage',
      'marsupials',
      'mascots',
      'mcu',
      'military',
      'mlb',
      'mls',
      'motown',
      'names',
      'occupations',
      'nfl',
      'nbl',
      'nhl',
      'punishment',
      'siblings',
      'shopping',
      'sitcoms',
      'socialism',
      'society_and_culture',
      'sociology',
      'straits',
      'suriname',
      'textiles',
      'the_incas',
      'time',
      'tonga',
      'units',
      'weapons',
      'young_adult',
    ],
  },
  Games: {
    Icon: GameIcon,
    keywords: [
      'billiards',
      'board_games',
      'card_games',
      'casinos',
      'chess',
      'gambling',
      'gameshows',
      'motor_racing',
      'puzzles',
      'racing',
      'snooker',
      'the_space_race',
      'video_games',
    ],
  },
  Movies: {
    Icon: MovieIcon,
    keywords: [
      'batman',
      'cult_films',
      'fantasy',
      'fiction',
      'fictitious_characters',
      'folklore',
      'film',
      'film_and_tv',
      'film_quotes',
      'films',
      'friends',
      'horror',
      'lord_of_the_rings',
      'marvel',
      'maroon_5',
      'neighbors',
      'opening_lines',
      'producers',
      'reality_tv',
      'romance',
      'romantic_comedies',
      'romeo_and_juliet',
      'soap_operas',
      'soundtracks',
      'star_trek',
      'star_wars',
      'the_simpsons',
      'superheroes',
      'superman',
    ],
  },
  Music: {
    Icon: MusicIcon,
    keywords: [
      'abba',
      'classical_music',
      'composers',
      'country_music',
      'cover_song',
      'jazz',
      'lyrics',
      'music',
      'music_albums',
      'music_theory',
      'musical_instruments',
      'musicals',
      'musicians',
      'rap',
      'rap_music',
      'reggae',
      'rock',
      'rock_and_roll',
      'rock_music',
      'singers',
      'singing',
      'songs',
      'soul_music',
      'sounds',
      'the_beatles',
    ],
  },
  Aviation: {
    Icon: AviationIcon,
    keywords: ['airlines', 'airports', 'aviation', 'arms'],
  },
  Programming: {
    Icon: ProgrammingIcon,
    keywords: ['software_engineering'],
  },
  Countries: {
    Icon: CountriesIcon,
    keywords: [
      'countries',
      'flags',
      'national symbols',
      'Sydney\n',
      'alaska',
      'albania',
      'algeria',
      'andorra',
      'angola',
      'argentina',
      'armenia',
      'antigua_and_barbuda',
      'azerbaijan',
      'atlanta',
      'australia',
      'austria',
      'bahrain',
      'baltimore',
      'bangladesh',
      'barbados',
      'barcelona',
      'beijing',
      'belgium',
      'belize',
      'benin',
      'berlin',
      'bhutan',
      'bolivia',
      'bosnia_and_herzegovina',
      'boston',
      'botswana',
      'brazil',
      'britain',
      'brunei',
      'bulgaria',
      'burkina_faso',
      'burundi',
      'california',
      'cambodia',
      'cameroon',
      'canada',
      'cape_verde',
      'celtic',
      'central_african_republic',
      'central_america',
      'chad',
      'chicago',
      'chile',
      'china',
      'city_of_westminster',
      'colombia',
      'comoros',
      'costa_rica',
      'croatia',
      'cuba',
      'cyprus',
      'aztecs',
      'dallas',
      'dc',
      'democratic_republic_of_the_congo',
      'denmark',
      'djibouti',
      'dominica',
      'dominican_republic',
      'ecuador',
      'east_timor',
      'egypt',
      'el_salvador',
      'england',
      'equatorial_guinea',
      'eritrea',
      'espionage',
      'eswatini',
      'federated_states_of_micronesia',
      'fiji',
      'florida',
      'france',
      'gabon',
      'georgia',
      'germany',
      'greece',
      'grenada',
      'guatemala',
      'guinea',
      'guinea-bissau',
      'guyana',
      'hawaii',
      'haiti',
      'hungary',
      'india',
      'indonesia',
      'iran',
      'iraq',
      'ireland',
      'israel',
      'istanbul',
      'italy',
      'ivory_coast',
      'japan',
      'jordan',
      'kansas',
      'kazakhstan',
      'kentucky',
      'kingdom_of_denmark',
      'kingdom_of_the_netherlands',
      'jamaica',
      'kiribati',
      'kuwait',
      'kyrgyzstan',
      'laos',
      'las_vegas',
      'latvia',
      'lebanon',
      'lesotho',
      'liberia',
      'libya',
      'liechtenstein',
      'liverpool',
      'london',
      'los_angeles',
      'louisiana',
      'madagascar',
      'madrid',
      'malawi',
      'malaysia',
      'maldives',
      'mali',
      'malta',
      'manchester',
      'marshall_islands',
      'massachusetts',
      'mauritania',
      'mauritius',
      'mexico',
      'miami',
      'michigan',
      'milan',
      'missouri',
      'moldova',
      'monaco',
      'mongolia',
      'montenegro',
      'morocco',
      'moscow',
      'mozambique',
      'myanmar',
      'namibia',
      'nauru',
      'nevada',
      'new_jersey',
      'nepal',
      'new_orleans',
      'new_york',
      'new_york_city',
      'new_zealand',
      'nicaragua',
      'niger',
      'nigeria',
      'north_korea',
      'north_macedonia',
      'norway',
      'ohio',
      'oklahoma',
      'oman',
      'pakistan',
      'palau',
      'panama',
      'papua_new_guinea',
      'paraguay',
      'paris',
      'peru',
      'philippines',
      'poland',
      'polynesia',
      'portugal',
      'qatar',
      'republic_of_the_congo',
      'romania',
      'rome',
      'russia',
      'rwanda',
      'saint_kitts_and_nevis',
      'saint_lucia',
      'saint_petersburg',
      'saint_vincent_and_the_grenadines',
      'salvador_dali',
      'samoa',
      'san_marino',
      'saudi_arabia',
      'scandinavia',
      'scotland',
      'seattle',
      'senegal',
      'serbia',
      'seychelles',
      'sierra_leone',
      'singapore',
      'solomon_islands',
      'somalia',
      'south_africa',
      'south_america',
      'south_korea',
      'south_sudan',
      'southampton',
      'southeast_asia',
      'soviet_union',
      'spain',
      'texas',
      'thailand',
      'the_bahamas',
      'the_gambia',
      'the_middle_east',
      'the_netherlands',
      'the_wild_west',
      'togo',
      'trinidad_and_tobago',
      'tunisia',
      'turkey',
      'turkmenistan',
      'tuvalu',
      'uganda',
      'uk',
      'ukraine',
      'united_arab_emirates',
      'united_kingdom',
      'sri_lanka',
      'st._louis',
      'state_of_palestine',
      'stockholm',
      'sweden',
      'sudan',
      'switzerland',
      'syria',
      'são_tomé_and_príncipe',
      'taiwan',
      'tajikistan',
      'tanzania',
      'us_states',
      'usa',
      'utah',
      'uzbekistan',
      'vanuatu',
      'vatican_city',
      'venezuela',
      'venice',
      'vietnam',
      'virginia',
      'washington_dc',
      'westerns',
      'wisconsin',
      'yemen',
      'zambia',
      'zimbabwe',
      'zulu',
    ],
  },
};

export default categoryGroups;
